In [1]:
import numpy as np

In [46]:
def eliminacion(u):

  a_rem = 0
  a = 0
  b = 0

  for j in range(0, len(u) - 1):

    for i in range(0,len(u)):

      if i == j and u[i,j] != 1:
        a = u[i,j]
        a_rem = u[i,j::] / a
        u[i,j::] = a_rem

      if u[i,j] != 1 and i != j and u[i,j] != 0:

        a = u[i,j]
        u[i,j::] = u[i,j::] - (a * u[j,j::])

      if u[i,j] == 1 and i != j:

        u[i,j::] = u[i,j::] - u[j,j::]

  u[len(u) - 1,len(u) - 1] = u[len(u) - 1,len(u) - 1] / u[len(u) - 1,len(u) - 1]

  #Segunda parte

  a = 0
  b = 0

  for i in range(0,len(u)):

    a = u[::,i]

    for j in range(0,len(u) - 1):

      if a[j] == 1. or a[j] == 0:

        pass

      else:

        a[j] = 0

  return u

In [50]:
a = 1.0 * np.random.randint(0,20,(3,3))
a

array([[12., 10.,  6.],
       [ 8.,  2., 10.],
       [15.,  3.,  2.]])

In [51]:
print(eliminacion(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
